color0               #151515
color8               #555555
color1               #fb413a
color9               #febab7
color2               #7ed68a
color10              #ebfaec
color3               #e58a2b
color11              #d8b65a
color4               #45566e
color12              #8295b1
color5               #d97aad
color13              #fbe9f2
color6               #e67eb3
color14              #fbe9f2
color7               #808080
color15              #e8e1cf

background           #151515
foreground           #e8e1cf
cursor               #d8b65a
selection_background #2c2c2c
selection_foreground #d8b65a
active_border_color  #7ed68a
mark1_foreground     #fb413a
mark1_background     #151515
mark2_foreground     #d8b65a
mark2_background     #151515
mark3_foreground     #7ed68a
mark3_background     #151515
