" Options {{{
set autoindent
set autoread
set backspace=indent,eol,start
set clipboard=unnamed
set completeopt=menuone,noselect
set display=lastline
set expandtab
set foldmethod=syntax
set ignorecase
set incsearch
set infercase
set keywordprg=:help
set laststatus=1
set linebreak
set mouse=a
set nocursorline
set nohlsearch
set nojoinspaces
set noruler
set noshowcmd
set noshowmode
set noswapfile
set notitle
set nowrap
set nonumber
set scrolloff=10
set shiftround
set shiftwidth=2
set shortmess=filnxtToOIcFsm
set sidescrolloff=5
set signcolumn=yes
set smartcase
set smarttab
set softtabstop=2
set tabstop=2
set tags=./tags;,tags;
set undodir=~/.vim/tmp/undo
set undofile
set undolevels=10000
set undoreload=10000
set updatetime=100
set wildignore+=.DS_Store,Icon\?,*.dmg,*.git,*.pyc,*.o,*.obj,*.so,*.swp,*.zip
set wildignorecase
set wildmenu
set grepformat^=%f:%l:%c:%m
set encoding=utf-8
set belloff=all
if executable('rg')
    set grepprg=rg\ -i\ --vimgrep
endif

" Disable netrw before calling filetype
let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1

filetype plugin indent on
" }}}

" Functions {{{
fun! s:CustomizeHighlight()
  highlight      SignColumn      guibg=NONE    ctermbg=NONE
  highlight      GitGutterAdd    guifg=#009900 ctermfg=2 guibg=NONE ctermbg=NONE
  highlight      GitGutterChange guifg=#bbbb00 ctermfg=3 guibg=NONE ctermbg=NONE
  highlight      GitGutterDelete guifg=#ff2222 ctermfg=1 guibg=NONE ctermbg=NONE
  highlight link GitGutterChangeDelete GitGutterChange

  highlight      VimspectorBP            guifg=#ff2222 ctermfg=1   guibg=NONE ctermbg=NONE
  highlight      VimspectorPC            guifg=#FFC7FC ctermfg=2   guibg=NONE ctermbg=NONE
  highlight      vimspectorCurrentThread guifg=#f09900 ctermfg=2   guibg=NONE ctermbg=NONE
  highlight      CursorLineNr  term=bold guifg=#fabd2f ctermfg=214 guibg=NONE ctermbg=NONE
  highlight      Normal                  guibg=NONE    ctermbg=NONE
  highlight      LineNr                  guibg=NONE    ctermbg=NONE
endf

fun! s:Highlight()
  redir @a | highlight | redir END | new | put a
endf

fun! s:CleanUndoFiles()
  !find ~/.vim/tmp/undo -type f -mtime +100d \! -name '.gitignore' -delete
endf
" }}}

" Appearance {{{
syntax enable

if has('termguicolors') && $COLORTERM ==# 'truecolor'
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif

set list
set cmdheight=1
set background=dark

let g:gruvbox_contrast_dark = 'hard'
let g:gruvbox_contrast_light = 'hard'

let &showbreak='└ '
let &fillchars='eob: '
let &listchars='tab:⋮ ,trail:·,extends:>,precedes:<,nbsp:+'
let &t_SI="\e[5 q"
let &t_SR="\e[4 q"
let &t_EI="\e[2 q"

autocmd VimEnter     * call echoraw(&t_EI)
autocmd CmdlineEnter * call echoraw(&t_SI)
autocmd CmdlineLeave * call echoraw(&t_EI)
autocmd ColorScheme  * call <SID>CustomizeHighlight()

colorscheme gruvbox
" }}}

" Mappings {{{
let mapleader = "\<Space>"

" Turn off linewise keys
nmap j gj
nmap k gk

nnoremap          <c-g>                 2<c-g>
nnoremap          Y                     y$
nnoremap          R                     :%s//g<Left><Left>
nnoremap          <leader>/             :Rg -g '!tags' ""<Left>
nnoremap          <leader>r             :History:<CR>
nnoremap <silent> <C-e>                 :e#<CR>
nnoremap <silent> yoz                   :call zoompane#Toggle()<CR>
nnoremap <silent> <leader>.             :GFiles<CR>
nnoremap <silent> <leader>k             :Helptags<CR>
nnoremap <silent> <leader>u             :UndotreeToggle<CR>
nnoremap <silent> <leader>b             :Buffers<CR>
nnoremap <silent> <leader>g             :Git<CR>
nnoremap <silent> <leader>j             :sp<CR>
nnoremap <silent> <leader>l             :vsp<CR>
nnoremap <silent> <leader>o             :Files<CR>
nnoremap <silent> <leader>p             :Commands<CR>
nnoremap <silent> <leader>q             :q<CR>
nnoremap <silent> <leader>s             :MicrolineToggle<CR>
nnoremap <silent> <leader>w             :w<CR>
nnoremap <silent> <leader>tb            :BTags<CR>
nnoremap <silent> <leader>tt            :Tags<CR>
nnoremap <silent> <leader>ec            :e ~/.vim/vimrc<CR>
nnoremap <silent> <leader>=h            :exe "resize +5"<CR>
nnoremap <silent> <leader>-h            :exe "resize -5"<CR>
nnoremap <silent> <leader>=v            :exe "vertical resize +5"<CR>
nnoremap <silent> <leader>-v            :exe "vertical resize -5"<CR>
" Break undo before deleting words and lines
inoremap <C-W> <C-G>u<C-W>
inoremap <C-U> <C-G>u<C-U>
" Move visual block up and down
xnoremap <silent> K                     :m '<-2<CR>gv=gv
xnoremap <silent> J                     :m '>+1<CR>gv=gv
" Search visual selection with ripgrep
xnoremap <silent> <leader>/             "yy:Rg -g '!tags' "<C-R>y"<CR>
" }}}

" Plugins {{{
" Man {{{
runtime ftplugin/man.vim
" }}}
" MatchIt {{{
packadd! matchit
" }}}
" FZF {{{
highlight FzfBorder guifg=#98971C

set rtp+=/usr/local/opt/fzf

let g:fzf_colors = { 'border':  ['fg', 'FzfBorder', 'Ignore'] }
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.8, 'border': 'rounded' } }
let g:fzf_preview_window = ['right:70%:hidden', 'ctrl-]']

nmap <silent>        <leader><tab>  <Plug>(fzf-maps-n)
omap <silent>        <leader><tab>  <Plug>(fzf-maps-o)
xmap <silent>        <leader><tab>  <Plug>(fzf-maps-x)
imap <silent>        <c-x><c-k>     <Plug>(fzf-complete-word)
imap <silent>        <c-x><c-l>     <Plug>(fzf-complete-line)
imap <silent>        <c-x><c-f>     <Plug>(fzf-complete-path)
imap <silent> <expr> <c-x><c-x>     custom#fzf#CompleteSnippet()
imap <silent> <expr> <c-x><c-o>     custom#fzf#CompleteNoteLink()
" }}}
" Rooter {{{
let g:rooter_patterns = ['.git', 'Makefile', 'package.json', 'init.vim', '.envrc']
" }}}
" VSnip {{{
let g:vsnip_snippet_dir = '~/.vim/snippets'
let g:vsnip_filetypes = {
      \ 'typescript': ['javascript'],
      \ 'javascriptreact': ['javascript'],
      \ 'typescriptreact': ['javascript'],
      \}

imap <silent> <expr> <Tab>    vsnip#jumpable(1)  ? '<Plug>(vsnip-jump-next)' : (pumvisible() ? '<C-n>' : '<Tab>')
imap <silent> <expr> <S-Tab>  vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : (pumvisible() ? '<C-p>' : '<S-Tab>')
imap <silent> <expr> <C-j>    vsnip#expandable() ? '<Plug>(vsnip-expand)'    : '<C-j>'
smap <silent> <expr> <Tab>    vsnip#jumpable(1)  ? '<Plug>(vsnip-jump-next)' : (pumvisible() ? '<C-n>' : '<Tab>')
smap <silent> <expr> <S-Tab>  vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : (pumvisible() ? '<C-p>' : '<S-Tab>')
smap <silent> <expr> <C-j>    vsnip#expandable() ? '<Plug>(vsnip-expand)'    : '<C-j>'
" }}}
" GH-Line {{{
let g:gh_line_map_default       = 0
let g:gh_line_blame_map_default = 0
let g:gh_repo_map               = '<leader><leader>go'
let g:gh_open_command           = 'fn() { echo "$@" | pbcopy; }; fn '
" }}}
" GitGutter {{{
let g:gitgutter_sign_added = '▌'
let g:gitgutter_sign_modified = '▌'
let g:gitgutter_sign_removed = '▌'
let g:gitgutter_sign_modified_removed = '∙'
nmap ]g :GitGutterNextHunk<CR>
nmap [g :GitGutterPrevHunk<CR>
" }}}
" Emmet {{{
let g:user_emmet_install_global = 0
" }}}
" indentLine {{{
let g:indentLine_fileType = ['yaml', 'yml']
" }}}
" EasyAlign {{{
xmap <silent> <leader>ea <Plug>(EasyAlign)
" }}}
" Goyo {{{
let g:goyo_width = 120

autocmd! User GoyoEnter call custom#goyo#GoyoEnter()
autocmd! User GoyoLeave call custom#goyo#GoyoLeave()
" }}}
" Undotree {{{
let g:undotree_DiffAutoOpen = 0
" }}}
" Copilot {{{
let g:copilot_filetypes = { 'fzf': v:false, 'dirvish': v:false }
" }}}
" Dirvish {{{
let g:dirvish_mode = ':sort ,^.*[\/],'
" }}}
" Context.vim {{{
let g:context_highlight_tag = '<hide>'
" }}}
" vim-slime {{{
let g:slime_target = "tmux"
" }}}
" Vimspector {{{
let g:vimspector_enable_winbar = 0
let g:vimspector_sign_priority = {
    \    'vimspectorBP':          998,
    \    'vimspectorBPCond':      998,
    \    'vimspectorBPLog':       998,
    \    'vimspectorBPDisabled':  998,
    \    'vimspectorNonActivePC': 998,
    \    'vimspectorPC':          999,
    \    'vimspectorPCBP':        999,
    \ }
sign define vimspectorBP            text=● texthl=VimspectorBP
sign define vimspectorBPCond        text=◆ texthl=VimspectorBP
sign define vimspectorBPLog         text=◆ texthl=VimspectorBP
sign define vimspectorBPDisabled    text=● texthl=LineNr
sign define vimspectorPC            text=→ texthl=VimspectorPC linehl=CursorLine
sign define vimspectorPCBP          text=→ texthl=VimspectorPC linehl=CursorLine
sign define vimspectorNonActivePC   linehl=DiffAdd
sign define vimspectorCurrentThread text=▶ texthl=VimspectorCurrentThread linehl=Normal
sign define vimspectorCurrentFrame  text=→ texthl=VimspectorCurrentThread linehl=Normal

nnoremap <silent> <F2>                  :call vimspector#Launch()<CR>
nnoremap <silent> <leader><F2>          :call vimspector#Reset()<CR>
nnoremap <silent> <F5>                  <Plug>VimspectorRestart
nnoremap <silent> <F8>                  <Plug>VimspectorContinue
nnoremap <silent> <leader><F8>          <Plug>VimspectorStop
nnoremap <silent> <F9>                  <Plug>VimspectorToggleBreakpoint
nnoremap <silent> <leader><F9>          <Plug>VimspectorToggleConditionalBreakpoint
nnoremap <silent> <F10>                 <Plug>VimspectorStepOver
nnoremap <silent> <F11>                 <Plug>VimspectorStepInto
nnoremap <silent> <F12>                 <Plug>VimspectorStepOut

autocmd! User VimspectorUICreated      call custom#vimspector#CustomiseUI()
autocmd! User VimspectorTerminalOpened call custom#vimspector#CustomiseTerminal()
" }}}
" CSS Color {{{
nnoremap <silent> <leader>tcc :call css_color#toggle()<CR>
" }}}
" }}}

" Autocommands {{{
autocmd FileType gitrebase,gitconfig setlocal bufhidden=delete | setlocal spell
autocmd BufNewFile,BufRead vimrc let g:gitgutter_git_args='--git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
autocmd FileChangedShellPost * echohl WarningMsg | echo "File changed on disk. Buffer reloaded." | echohl None
autocmd BufRead,BufNewFile *.gdip set filetype=gdresource
" }}}

" Commands {{{
command  -nargs=0        Highlight        call <SID>Highlight()
command  -nargs=0        CleanUndoFiles   call <SID>CleanUndoFiles()
command  -nargs=0        QfBuffers        call quickfix#AddOpenBuffersToList()
command  -nargs=1        QfReadFromFile   call quickfix#ReadListFromFile(<f-args>)
command  -nargs=0        RemoveQfItem     call quickfix#RemoveItem()
command  -nargs=0        FzfGitCheckout   call custom#fzf#GitCheckoutBranch()
command! -nargs=* -bang  Rg               call custom#fzf#RgExcludeFilenames(<q-args>, <bang>0)
" }}}

" vim: set sw=2 ts=2 sts=0 expandtab fdm=marker :nospell:
