" --== Settings --==

set clipboard=unnamed
set cursorline
set fillchars=eob:\ 
set laststatus=1
set list
set listchars=tab:⋮\ ,trail:·,extends:>,precedes:<,nbsp:+
set mouse=a
set nohlsearch
set noruler
set noshowcmd
set noshowmode
set noswapfile
set number
set scrolloff=1
set shortmess=filnxtToOIcFs
set signcolumn=yes
set smartcase
set termguicolors
set updatetime=300
set foldmethod=syntax

" --== Appearance --==

syntax on
colorscheme lunaperche

" Set terminal codes for cursor shapes per mode
let &t_SI="\e[5 q" " [ INSERT ]  - blinking bar
let &t_SR="\e[4 q" " [ REPLACE ] - steady underline
let &t_EI="\e[2 q" " [ NORMAL ]  - steady block

autocmd VimEnter     * call echoraw(&t_EI)
autocmd CmdlineEnter * call echoraw(&t_SI)
autocmd CmdlineLeave * call echoraw(&t_EI)

" --== Plugin Settings --==

" Add Homebrew installed fzf to runtimepath
set rtp+=/usr/local/opt/fzf

let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.7, 'relative': v:true } }
let g:fzf_preview_window = ['down:70%:hidden', 'ctrl-]']

let g:rooter_silent_chdir = 1
let g:rooter_patterns = ['.git', 'Makefile', 'package.json', 'init.vim', '.envrc']
let g:rooter_change_directory_for_non_project_files = 'current'

let g:vsnip_filetypes = {
     		\ 'typescript': ['javascript'],
     		\ 'javascriptreact': ['javascript'],
     		\ 'typescriptreact': ['javascript'],
     		\}
let g:vsnip_snippet_dir = system('echo -n $HOME/.vim/snippets')

let g:gh_repo_map = '<leader><leader>go'
let g:gh_line_map_default = 0
let g:gh_line_blame_map_default = 0
let g:gh_open_command = 'fn() { echo "$@" | pbcopy; }; fn '

let g:user_emmet_install_global = 0

let g:indentLine_fileType = ['yaml', 'yml']

let g:goyo_width = 120

let g:undotree_DiffAutoOpen = 0

let g:copilot_filetypes = { 'dap-repl': v:false }

let g:netrw_home=$XDG_CACHE_HOME.'/vim'

let g:vimspector_enable_winbar = 0
let g:vimspector_sidebar_width = 50
let g:vimspector_code_minwidth = 90

" --== Mappings --==

let mapleader = "\<Space>"

" Break undo before deleting a word
inoremap <C-W> <C-G>u<C-W>

" Break undo before deleting a line
inoremap <C-U> <C-G>u<C-U>

nmap          R                     :%s//g<Left><Left>
nmap          <leader>/             :Rg -g '!tags' ""<Left>
nmap          <leader>r             :History:<CR>
nmap <silent> K                     :call utils#VimHelp()<CR>
nmap <silent> yoz                   :call utils#ZoomPane()<CR>
nmap <silent> <F2>                  :call vimspector#Launch()<CR>
nmap <silent> <leader><F2>          :call vimspector#Reset()<CR>
nmap <silent> <F5>                  <Plug>VimspectorRestart
nmap <silent> <F8>                  <Plug>VimspectorContinue
nmap <silent> <leader><F8>          <Plug>VimspectorStop
nmap <silent> <F9>                  <Plug>VimspectorToggleBreakpoint
nmap <silent> <leader><F9>          <Plug>VimspectorToggleConditionalBreakpoint
nmap <silent> <F10>                 <Plug>VimspectorStepOver
nmap <silent> <F11>                 <Plug>VimspectorStepInto
nmap <silent> <F12>                 <Plug>VimspectorStepOut
nmap <silent> <leader>.             :GFiles<CR>
nmap <silent> <leader>u             :UndotreeToggle<CR>
nmap <silent> <leader>b             :Buffers<CR>
nmap <silent> <leader>g             :Git<CR>
nmap <silent> <leader>j             :sp<CR>
nmap <silent> <leader>l             :vsp<CR>
nmap <silent> <leader>o             :Files<CR>
nmap <silent> <leader>p             :Commands<CR>
nmap <silent> <leader>q             :q<CR>
nmap <silent> <leader>s             :MicrolineToggle<CR>
nmap <silent> <leader>w             :w<CR>
nmap <silent> <leader>tb            :BTags<CR>
nmap <silent> <leader>tt            :Tags<CR>
nmap <silent> <leader>ec            :e ~/.vim/vimrc<CR>
nmap <silent> <leader>=h            :exe "resize +5"<CR>
nmap <silent> <leader>-h            :exe "resize -5"<CR>
nmap <silent> <leader>=v            :exe "vertical resize +5"<CR>
nmap <silent> <leader>-v            :exe "vertical resize -5"<CR>
nmap <silent> <leader>tcc           :call css_color#toggle()<CR>
nmap <silent> <leader><tab>         <Plug>(fzf-maps-n)

omap <silent> <leader><tab>         <Plug>(fzf-maps-o)

xmap <silent>        <leader>ea     <Plug>(EasyAlign)
xmap <silent>        <leader>ys     <Plug>(VSurround)
xmap <silent>        <leader><tab>  <Plug>(fzf-maps-x)
xmap <silent>        <leader>/      "yy:Rg -g '!tags' "<C-R>y"<CR>

imap <silent>        <c-x><c-k>     <Plug>(fzf-completing-word)
imap <silent>        <c-x><c-l>     <Plug>(fzf-completing-line)
imap <silent>        <c-x><c-f>     <Plug>(fzf-completing-path)
imap <silent> <expr> <c-x><c-x>     utils#FzfCompleteSnippet()
imap <silent> <expr> <c-x><c-o>     utils#FzfCompleteNoteLink()

imap <silent> <expr> <Tab>          vsnip#jumpable(1)  ? '<Plug>(vsnip-jump-next)' : (pumvisible() ? '<C-n>' : utils#HandleTab())
imap <silent> <expr> <S-Tab>        vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : (pumvisible() ? '<C-p>' : '<S-Tab>')
imap <silent> <expr> <C-j>          vsnip#expandable() ? '<Plug>(vsnip-expand)'    : '<C-j>'

smap <silent> <expr> <C-j>          vsnip#expandable() ? '<Plug>(vsnip-expand)'    : '<C-j>'
smap <silent> <expr> <Tab>          vsnip#jumpable(1)  ? '<Plug>(vsnip-jump-next)' : (pumvisible() ? '<C-n>' : utils#HandleTab())
smap <silent> <expr> <S-Tab>        vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : (pumvisible() ? '<C-p>' : '<S-Tab>')

" --== Autocommands --==

autocmd FileType gdscript
			\  let b:start='/Applications/Godot.app/Contents/MacOS/Godot'

autocmd FileType fugitive
			\  nmap <buffer> <silent> gb :call utils#FzfGitCheckoutBranch()<CR>

autocmd FileType markdown
			\  setlocal shiftwidth=2
			\| setlocal foldlevel=99

autocmd FileType html,css
			\  setlocal shiftwidth=2
			\| setlocal foldlevel=99
			\| EmmetInstall

autocmd FileType c,cpp
			\  setlocal tabstop=4
			\| setlocal shiftwidth=4
			\| setlocal foldlevel=99
			\| compiler make

autocmd FileType json
			\  setlocal expandtab
			\| setlocal tabstop=2
			\| setlocal shiftwidth=2
			\| setlocal foldlevel=2

autocmd FileType yaml
			\ setlocal foldlevel=4

autocmd FileType javascript,javascriptreact
			\  setlocal expandtab
			\| setlocal tabstop=2
			\| setlocal shiftwidth=2
			\| setlocal foldlevel=99
			\| setlocal suffixesadd=.js,.jsx,.ts,.tsx
			\| compiler eslint
			\| let maplocalleader="\\"
			\| EmmetInstall

autocmd FileType typescript,typescriptreact
			\  setlocal expandtab
			\| setlocal tabstop=4
			\| setlocal shiftwidth=4
			\| setlocal foldlevel=99
			\| setlocal suffixesadd=.js,.jsx,.ts,.tsx
			\| compiler tsc
			\| let maplocalleader="\\"
			\| map <localleader>e :Dispatch -compiler=eslint<CR>
			\| EmmetInstall

autocmd FileType repl
			\  setlocal filetype=bash

autocmd FileType netrw
			\  nmap <buffer> h -
			\| nmap <buffer> l <CR>
			\| nmap <buffer> <ESC> <C-^>
			\| nmap <buffer> ff %:w<CR>:buffer #<CR>

autocmd FileType qf
			\ map <buffer> dd :call utils#RemoveQfItem()<CR>

autocmd FileType gitcommit,gitrebase,gitconfig
			\ set bufhidden=delete

autocmd BufNewFile,BufRead init.vim
			\ let g:gitgutter_git_args='--git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

autocmd! User GoyoEnter nested 
			\ call utils#GoyoEnter()

autocmd! User GoyoLeave nested
			\ call utils#GoyoLeave()

" Triger `autoread` when files change on disk
autocmd FileChangedShellPost * echohl WarningMsg | echo "File changed on disk. Buffer reloaded." | echohl None

autocmd FocusGained,BufEnter,CursorHold,CursorHoldI * if mode() !~ '\v(c|r.?|!|t)' && getcmdwintype() == '' | checktime | endif

" --== Commands --==

command!                Gqf       GitGutterQuickFix | copen
command!                Highlight call utils#Highlight()
command!                BuffersQf call setqflist(map(filter(range(1, bufnr('$')), 'buflisted(v:val)'), '{"bufnr":v:val}')) | copen
command! -nargs=1       ReadToQF  call utils#ReadQfListFromFile(<f-args>)
command! -nargs=* -bang Rg        call utils#FzfExcludeFilenamesFromRg(<q-args>, <bang>0)
