" Options {{{
set nocompatible
set encoding=utf-8
set autoindent
set autoread
set backspace=indent,eol,start
set completeopt=menuone,preview
set display=lastline
set foldmethod=indent
set ignorecase
set noinfercase
set incsearch
set smartcase
set keywordprg=:help
set laststatus=2
set linebreak
set mouse=a
set cursorline
set cursorlineopt=number
set nohlsearch
set nojoinspaces
set noruler
set noshowcmd
set noshowmode
set noswapfile
set viminfofile=$XDG_CACHE_HOME/viminfo
set notitle
set titlestring=%<%F
set wrap
set number
set smarttab
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set shiftround
set shortmess=aoOstTIcF
set sidescroll=1
set sidescrolloff=2
set signcolumn=yes
set tags=./tags;,tags;
set undodir=~/.vim/tmp/undo
set undofile
set undolevels=10000
set updatetime=100
set history=1000
set wildmenu
set wildignorecase
set wildignore+=.DS_Store,Icon\?,*.dmg,*.git,*.pyc,*.o,*.obj,*.so,*.swp,*.zip
set belloff=all
set formatoptions+=j
set complete-=i
set viewoptions-=options
set sessionoptions-=options
set nrformats=bin,hex
set ttimeout
set ttimeoutlen=100
set path+=**
set t_vb=
set noerrorbells
set noequalalways
if has('macunix')
  set clipboard=unnamed
elseif has('unix')
  set clipboard=unnamedplus
endif
set foldlevel=99

" Disable netrw before calling filetype
let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1

filetype plugin indent on
" }}}

" Appearance {{{
syntax enable

set list
set cmdheight=1
set tabline=%!Picotab()

if has('termguicolors') && $COLORTERM ==# 'truecolor'
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif

let &showbreak='└ '
let &fillchars='eob: '
let &listchars='tab:▏ ,trail:·,extends:>,precedes:<,nbsp:+'
let &t_SI="\e[5 q"
let &t_SR="\e[4 q"
let &t_EI="\e[2 q"

colorscheme gman
" }}}

" Mappings {{{
let mapleader = "\<Space>"
let maplocalleader = "\\"

nnoremap          j                     gj
nnoremap          k                     gk
nnoremap <silent> X                     :tabclose<CR>
nnoremap <silent> H                     :TabMoveOrCreate h<CR>
nnoremap <silent> L                     :TabMoveOrCreate l<CR>
nnoremap <silent> <C-w>h                :WinMoveOrSplit h<CR>
nnoremap <silent> <C-w>j                :WinMoveOrSplit j<CR>
nnoremap <silent> <C-w>k                :WinMoveOrSplit k<CR>
nnoremap <silent> <C-w>l                :WinMoveOrSplit l<CR>
nnoremap <silent> <C-A-h>               :vertical resize -5<CR>
nnoremap <silent> <C-A-j>               :resize +5<CR>
nnoremap <silent> <C-A-k>               :resize -5<CR>
nnoremap <silent> <C-A-l>               :vertical resize +5<CR>
nnoremap <silent> yoz                   :WinZoom<CR>
nnoremap <silent> c*                    /\<<C-R>=expand('<cword>')<CR>\>\C<CR>``cgn
nnoremap <silent> c#                    ?\<<C-R>=expand('<cword>')<CR>\>\C<CR>``cgN
nnoremap <silent> d*                    /\<<C-r>=expand('<cword>')<CR>\>\C<CR>``dgn
nnoremap <silent> d#                    ?\<<C-r>=expand('<cword>')<CR>\>\C<CR>``dgN
nnoremap          Q                     :qa<CR>
nnoremap          Y                     y$
nnoremap          R                     :%s//g<Left><Left>
nnoremap <silent> <C-w>{                :pclose<CR>
nnoremap <silent> <C-g>                 2<C-g>
nnoremap <silent> <leader>w             :w<CR>
nnoremap          <leader>b             :buffer<Space>
nnoremap          <leader>f             :vimgrep // %<Left><Left><Left>
nnoremap <silent> <leader>ec            :e $MYVIMRC<CR>
nnoremap          <leader>re            :so $MYVIMRC<Bar>echomsg "vimrc reloaded"<CR>
nnoremap <silent> <C-]>                 :ltag <C-R><C-W><CR>
nnoremap <silent> 0                     :ToggleMovement ^ 0<CR>
nnoremap          <leader>yt            :YankCurrentDate<CR>
nnoremap          <leader>yf            :YankAbsoluteFilePath<CR>
nnoremap          <leader>yr            :YankRelativeFilePath<CR>
nnoremap          <leader>:             :Term<Space>
xnoremap <silent> K                     :m '<-2<CR>gv=gv
xnoremap <silent> J                     :m '>+1<CR>gv=gv
xnoremap <silent> <localleader>d        :s/\d\+/\=submatch(0)-1/g<CR>
xnoremap <silent> <localleader>i        :s/\d\+/\=submatch(0)+1/g<CR>
xnoremap          gh                    :GithubBrowse<CR>
inoremap          <C-w>                 <C-g>u<C-w>
inoremap          <C-u>                 <C-g>u<C-u>
" }}}

" Plugins {{{
let g:picopack = [
  \ 'MaxMEllon/vim-jsx-pretty',
  \ 'Yggdroot/indentLine',
  \ 'airblade/vim-gitgutter',
  \ 'ap/vim-css-color',
  \ 'guychouk/vim-picoline',
  \ 'habamax/vim-godot',
  \ 'junegunn/fzf',
  \ 'junegunn/fzf.vim',
  \ 'junegunn/gv.vim',
  \ 'junegunn/vim-easy-align',
  \ 'junegunn/vim-peekaboo',
  \ 'justinmk/vim-dirvish',
  \ 'markonm/traces.vim',
  \ 'mbbill/undotree',
  \ 'preservim/tagbar',
  \ 'psliwka/vim-smoothie',
  \ 'tpope/vim-abolish',
  \ 'tpope/vim-characterize',
  \ 'tpope/vim-commentary',
  \ 'tpope/vim-dispatch',
  \ 'tpope/vim-eunuch',
  \ 'tpope/vim-fugitive',
  \ 'tpope/vim-repeat',
  \ 'tpope/vim-rsi',
  \ 'tpope/vim-speeddating',
  \ 'tpope/vim-surround',
  \ 'tpope/vim-unimpaired',
  \ 'wellle/context.vim',
\ ]
nnoremap <silent> <leader>gg            :Git<CR>
nnoremap <silent> <leader>gb            :Branches<CR>
nnoremap <silent> <leader>cr            :ReviewBranch<CR>
nnoremap <silent> <leader>p             :Files<CR>
nnoremap <silent> <leader>.             :GFiles<CR>
nnoremap <silent> <leader>r             :History:<CR>
nnoremap <silent> <leader>u             :UndotreeToggle<CR>
nnoremap <silent> <leader>s             :PicolineToggle<CR>
nnoremap          <leader>/             :Dispatch grep -rn<Space>
nnoremap <silent> <leader>cs            :call css_color#toggle()<CR>
nnoremap <silent> <leader>hd            :GitGutterPreviewHunk<CR>
nnoremap <silent> <leader>hu            :GitGutterUndoHunk<CR>
nnoremap <silent> <leader>hs            :GitGutterStageHunk<CR>
nnoremap <silent> <leader>hp            :CommentOnPRLine<CR>
nnoremap          <leader>tb            :TagbarOpenAutoClose<CR>
nnoremap          <leader>tt            :Tags<Space>
xnoremap <silent> <leader>t             y:<C-U>Tags <C-R>"<CR>
nnoremap <silent> yoc                   :ContextToggle<CR>
nnoremap <silent> yop                   :IndentLinesToggle<CR>
nnoremap          <localleader>o        :Dispatch! open (pbpaste)<CR>
nnoremap          gz                    <Plug>(characterize)
nnoremap          ga                    <Plug>(EasyAlign)
xnoremap          ga                    <Plug>(EasyAlign)
xnoremap <silent> <leader><Tab>         <Plug>(fzf-maps-x)
onoremap <silent> <leader><Tab>         <Plug>(fzf-maps-o)
inoremap <silent> <C-x><C-f>            <Plug>(fzf-complete-path)
" Man {{{
runtime ftplugin/man.vim
" }}}
" MatchIt {{{
packadd! matchit
" }}}
" cfilter {{{
packadd! cfilter
" }}}
" comment {{{
" packadd! comment
" }}}
" FZF {{{
let g:fzf_colors = { 'border':  ['fg', 'FzfBorder', 'Ignore'] }
let g:fzf_layout = { 'window': { 'width': 0.7, 'height': 0.6, 'border': 'rounded' } }
let g:fzf_preview_window = ['right:70%:hidden', 'ctrl-]']
" }}}
" GitGutter {{{
let g:gitgutter_map_keys = 0
let g:gitgutter_sign_added = '▌'
let g:gitgutter_sign_modified = '▌'
let g:gitgutter_sign_removed = '▌'
let g:gitgutter_sign_modified_removed = '▌'
" }}}
" indentLine {{{
let g:indentLine_fileType = ['yaml', 'yml', 'python', 'gdscript']
" }}}
" Undotree {{{
let g:undotree_DiffAutoOpen = 0
" }}}
" Dirvish {{{
let g:dirvish_mode = ':sort ,^.*[\/],'
" }}}
" Context.vim {{{
let g:context_enabled = 0
let g:context_add_mappings = 0
let g:context_highlight_tag = '<hide>'
" }}}
" Godot {{{
let g:godot_executable = '/Applications/Godot.app/Contents/MacOS/Godot --position 1500,0'
" }}}
" Markdown {{{
let g:markdown_fenced_languages = ['python','javascript','typescript','bash=sh','html','vim','conf','sql','proto','go']
" }}}
" }}}

" Autocommands {{{

augroup appearance_settings
  autocmd!
  autocmd VimEnter     * call echoraw(&t_EI)
  autocmd CmdlineEnter * call echoraw(&t_SI)
  autocmd CmdlineLeave * call echoraw(&t_EI)
augroup END

augroup quickfix
  autocmd!
  autocmd VimEnter        *     cwindow
  autocmd QuickFixCmdPost l*    lwindow
  autocmd QuickFixCmdPost [^l]* cwindow
  autocmd FileType        qf    map <buffer> dd :RemoveQfItem<CR>
augroup END

augroup filetype_settings
  autocmd!

  " Dirvish
  autocmd FileType dirvish nmap <buffer> <localleader>v .kitty icat<CR>
  autocmd FileType dirvish nmap <buffer> t :call dirvish#open('tabedit', 0)<CR>
  autocmd FileType dirvish xmap <buffer> t :call dirvish#open('tabedit', 0)<CR>

  " Tagbar
  autocmd FileType tagbar setlocal foldlevel=99

  " Help
  autocmd FileType help nmap <buffer> q :close<CR>
  autocmd FileType help setlocal buflisted

  " zed (spicedb)
  autocmd FileType zed setlocal noexpandtab

  " Man
  autocmd FileType man setlocal hlsearch
  autocmd FileType man nmap <buffer> q :q<CR>

  " Shell
  autocmd FileType sh,bash,zsh compiler shellcheck

  " YAML
  autocmd FileType yaml setlocal foldlevel=2
  autocmd FileType yaml setlocal foldmethod=indent

  " Palette (vim-css-color)
  autocmd FileType palette call css_color#init('hex', 'basic', 'paletteComment')

  " C
  autocmd FileType c setlocal tabstop=4
  autocmd FileType c setlocal shiftwidth=4
  autocmd FileType c nmap <buffer> <localleader>b :Dispatch! nob<CR>

  " Proto
  autocmd FileType proto nmap <buffer> <localleader>l :Dispatch buf format -w<CR>

  " Nix
  autocmd FileType nix nmap <buffer> <localleader>r :Term ++rows=10 nix-instantiate --eval %<CR>

  " Vim
  autocmd FileType vim nmap <buffer> <localleader>m :SearchVimPackages<CR>

  " Go
  autocmd FileType go compiler go
  autocmd FileType go nmap <buffer> <localleader>b :Dispatch go build %<CR>
  autocmd FileType go nmap <buffer> <localleader>r :Term ++rows=10 go run %<CR>
  autocmd FileType go nmap <buffer> <localleader>l :Dispatch gofmt -w %<CR>
  autocmd FileType go nmap <buffer> <localleader>m :SearchGoPackages<CR>

  " Godot
  autocmd FileType gdscript setlocal foldmethod=expr
  autocmd FileType gdscript nmap <buffer> <localleader>r :GodotRun<CR>
  autocmd FileType gdscript nmap <buffer> <localleader>c :GodotRunCurrent<CR>
  autocmd FileType gdscript nmap <buffer> <localleader>d :GodotDocs<CR>

  " Git
  autocmd FileType gitcommit,gitrebase setlocal spell
  autocmd FileType gitcommit,gitrebase setlocal bufhidden=delete

  " JSON/JSONC
  autocmd FileType json,jsonc setlocal foldlevel=2
  autocmd FileType json,jsonc setlocal conceallevel=2

  " Markdown
  autocmd FileType markdown setlocal conceallevel=2
  autocmd FileType markdown setlocal nonumber
  autocmd FileType markdown setlocal wrap

  " Python
  autocmd FileType python nmap <buffer> <localleader>m :SearchPythonPackages<CR>

  " JavaScript
  autocmd FileType javascript,javascriptreact setlocal tabstop=4
  autocmd FileType javascript,javascriptreact setlocal shiftwidth=4
  autocmd FileType javascript,javascriptreact setlocal suffixesadd=.js,.jsx,.ts,.tsx
  autocmd FileType javascript,javascriptreact nmap <buffer> <localleader>m :SearchNodeModules<CR>
  autocmd FileType javascript,javascriptreact nmap <buffer> <localleader>b :Dispatch tsc %<CR>
  autocmd FileType javascript,javascriptreact nmap <buffer> <localleader>l :Dispatch eslint %<CR>
  autocmd FileType javascript,javascriptreact nmap <buffer> <localleader>r :Dispatch node %<CR>

  " TypeScript
  autocmd FileType typescript,typescriptreact setlocal tabstop=2
  autocmd FileType typescript,typescriptreact setlocal shiftwidth=2
  autocmd FileType typescript,typescriptreact setlocal suffixesadd=.js,.jsx,.ts,.tsx
  autocmd FileType typescript,typescriptreact nmap <buffer> <localleader>m :SearchNodeModules<CR>
  autocmd FileType typescript,typescriptreact nmap <buffer> <localleader>b :Dispatch tsc %<CR>
  autocmd FileType typescript,typescriptreact nmap <buffer> <localleader>l :Dispatch eslint %<CR>
  autocmd FileType typescript,typescriptreact nmap <buffer> <localleader>r :Dispatch ts-node %<CR>

augroup END
" }}}

" vim: set sw=2 ts=2 sts=0 expandtab fdm=marker :nospell:
