" Options {{{
set autoindent
set autoread
set backspace=indent,eol,start
set clipboard=unnamed
set completeopt=menuone
set display=lastline
set expandtab
set foldmethod=syntax
set ignorecase
set incsearch
set infercase
set keywordprg=:help
set laststatus=1
set linebreak
set mouse=a
set cursorline
set cursorlineopt=number
set nohlsearch
set nojoinspaces
set noruler
set noshowcmd
set noshowmode
set noswapfile
set notitle
set nowrap
set number
set scrolloff=10
set shiftround
set shiftwidth=2
set shortmess=filnxtToOIcFsm
set sidescrolloff=5
set signcolumn=yes
set smartcase
set smarttab
set softtabstop=2
set tabstop=2
set tags=./tags;,tags;
set undodir=~/.vim/tmp/undo
set undofile
set undolevels=10000
set undoreload=10000
set updatetime=100
set wildignore+=.DS_Store,Icon\?,*.dmg,*.git,*.pyc,*.o,*.obj,*.so,*.swp,*.zip
set wildignorecase
set wildmenu
set grepformat^=%f:%l:%c:%m
set encoding=utf-8
set belloff=all
if executable('rg')
    set grepprg=rg\ -i\ --vimgrep
endif

" Disable netrw before calling filetype
let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1

filetype plugin indent on
" }}}

" Functions {{{
fun! s:RefreshColorscheme()
  " Set background based on system appearance
  if system("defaults read -g AppleInterfaceStyle") =~ '^Dark'
    set background=dark
  else
    set background=light
  endif
endf

fun! s:Highlight()
  redir @a | highlight | redir END | new | put a
endf

fun! s:CleanUndoFiles()
  !find ~/.vim/tmp/undo -type f -mtime +100d \! -name '.gitignore' -delete
endf

fun! ConvertTimestampToISO()
  " Get the selected text
  let l:timestamp = getline(".")[col("'<") - 1 : col("'>") - 1]
  " Use Python to convert the timestamp to ISO 8601 with milliseconds
  let l:iso_time = system("python3 -c 'from datetime import datetime; import sys; timestamp=int(sys.argv[1]); print(datetime.utcfromtimestamp(timestamp).strftime(\"%Y-%m-%dT%H:%M:%S.%f\")[:-3] + \"Z\")' " . l:timestamp)
  " Remove any trailing newline
  let l:iso_time = substitute(l:iso_time, '\n', '', 'g')
  " Replace the timestamp with the ISO time
  call setline(".", substitute(getline("."), l:timestamp, l:iso_time, ""))
endf

fun! SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endf
" }}}

" Appearance {{{
syntax enable

if has('termguicolors') && $COLORTERM ==# 'truecolor'
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif

set list
set cmdheight=1

let &showbreak='└ '
let &fillchars='eob: '
let &listchars='tab:⋮ ,trail:·,extends:>,precedes:<,nbsp:+'
let &t_SI="\e[5 q"
let &t_SR="\e[4 q"
let &t_EI="\e[2 q"

autocmd VimEnter     * call echoraw(&t_EI)
autocmd CmdlineEnter * call echoraw(&t_SI)
autocmd CmdlineLeave * call echoraw(&t_EI)
autocmd ColorScheme  * call <SID>RefreshColorscheme()

" Set up colorscheme
colorscheme busy-g
call <SID>RefreshColorscheme()
" }}}

" Mappings {{{
let mapleader = "\<Space>"
let maplocalleader = "\\"

" Turn off linewise keys
nmap j gj
nmap k gk

nnoremap          <c-g>                 2<c-g>
nnoremap          Y                     y$
nnoremap          R                     :%s//g<Left><Left>
nnoremap          <leader>/             :Grep<Space>
nnoremap          <leader>r             :History:<CR>
nnoremap <silent> <C-e>                 :e#<CR>
nnoremap <silent> yoz                   :call zoompane#Toggle()<CR>
nnoremap <silent> <leader>o             :Files<CR>
nnoremap <silent> <leader>t             :Tags<CR>
nnoremap <silent> <leader>.             :GFiles<CR>
nnoremap <silent> <leader>u             :UndotreeToggle<CR>
nnoremap          <leader>b             :buffer<Space>
nnoremap <silent> <leader>g             :Git<CR>
nnoremap <silent> <leader>j             :sp<CR>
nnoremap <silent> <leader>l             :vsp<CR>
nnoremap <silent> <leader>q             :q<CR>
nnoremap <silent> <leader>s             :MicrolineToggle<CR>
nnoremap <silent> <leader>w             :w<CR>
nnoremap <silent> <leader>ec            :e ~/.vim/vimrc<CR>
nnoremap <silent> <localleader>q        :call quickfix#ToggleQuickfix()<CR>
" Right align word under cursor
nnoremap <silent> <leader><tab>         mc80A <esc>080lDgelD`cP
" Break undo before deleting words and lines
inoremap <C-W> <C-G>u<C-W>
inoremap <C-U> <C-G>u<C-U>
" Move visual block up and down
xnoremap <silent> K                     :m '<-2<CR>gv=gv
xnoremap <silent> J                     :m '>+1<CR>gv=gv
" Search visual selection with ripgrep
xnoremap <silent> <leader>/             "yy:Rg -g '!tags' "<C-R>y"<CR>
vnoremap <leader>t                      :<C-U>call ConvertTimestampToISO()<CR>
" }}}

" Plugins {{{
" Man {{{
runtime ftplugin/man.vim
" }}}
" MatchIt {{{
packadd! matchit
" }}}
" FZF {{{

set rtp+=/usr/local/opt/fzf

let g:fzf_colors = { 'border':  ['fg', 'FzfBorder', 'Ignore'] }
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.8, 'border': 'rounded' } }
let g:fzf_preview_window = ['right:70%:hidden', 'ctrl-]']

omap <silent>        <leader><tab>  <Plug>(fzf-maps-o)
xmap <silent>        <leader><tab>  <Plug>(fzf-maps-x)
imap <silent>        <c-x><c-k>     <Plug>(fzf-complete-word)
imap <silent>        <c-x><c-l>     <Plug>(fzf-complete-line)
imap <silent>        <c-x><c-f>     <Plug>(fzf-complete-path)
imap <silent> <expr> <c-x><c-x>     custom#fzf#CompleteSnippet()
imap <silent> <expr> <c-x><c-o>     custom#fzf#CompleteNoteLink()
" }}}
" Rooter {{{
let g:rooter_patterns = ['.git', 'Makefile', 'package.json', 'init.vim', '.envrc']
" }}}
" GH-Line {{{
let g:gh_line_map_default       = 0
let g:gh_line_blame_map_default = 0
let g:gh_repo_map               = '<leader><leader>go'
let g:gh_open_command           = 'fn() { echo "$@" | pbcopy; }; fn '
" }}}
" GitGutter {{{
let g:gitgutter_sign_added = '▌'
let g:gitgutter_sign_modified = '▌'
let g:gitgutter_sign_removed = '▌'
let g:gitgutter_sign_modified_removed = '∙'
nmap ]g :GitGutterNextHunk<CR>
nmap [g :GitGutterPrevHunk<CR>
" }}}
" Emmet {{{
let g:user_emmet_install_global = 0
" }}}
" indentLine {{{
let g:indentLine_fileType = ['yaml', 'yml']
" }}}
" EasyAlign {{{
xmap <silent> <leader>ea <Plug>(EasyAlign)
" }}}
" Goyo {{{
let g:goyo_width = 120
" }}}
" Undotree {{{
let g:undotree_DiffAutoOpen = 0
" }}}
" Copilot {{{
let g:copilot_filetypes = { 'fzf': v:false, 'dirvish': v:false }
let g:copilot_enabled = 0
imap <silent> <c-x><c-p> <Plug>(copilot-suggest)
" }}}
" Dirvish {{{
let g:dirvish_mode = ':sort ,^.*[\/],'
call dirvish#add_icon_fn({p -> p[-1:]=='/'?'📂 ':'📄 '})
" }}}
" Context.vim {{{
let g:context_highlight_tag = '<hide>'
" }}}
" vim-slime {{{
let g:slime_target = "tmux"
" }}}
" CSS Color {{{
nnoremap <silent> <leader>tcc :call css_color#toggle()<CR>
" }}}
" vim-minisnip {{{
let g:minisnip_dir = '~/.vim/snippets'
let g:minisnip_trigger = '<C-j>'
" }}}
" vim-gutentags {{{
let g:gutentags_enabled = 1
let g:gutentags_project_root = ['.git', '.ctags']
" }}}
" }}}

" Autocommands {{{
autocmd FileChangedShellPost * echohl WarningMsg | echo "File changed on disk. Buffer reloaded." | echohl None
autocmd SigUSR1 * call <SID>RefreshColorscheme()
" }}}

" Commands {{{
command  -nargs=0        Highlight        call <SID>Highlight()
command  -nargs=0        CleanUndoFiles   call <SID>CleanUndoFiles()
command  -nargs=0        QfBuffers        call quickfix#AddOpenBuffersToList()
command  -nargs=1        QfReadFromFile   call quickfix#ReadListFromFile(<f-args>)
command  -nargs=0        RemoveQfItem     call quickfix#RemoveItem()
command  -nargs=0        FzfGitCheckout   call custom#fzf#GitCheckoutBranch()
command! -nargs=* -bang  Rg               call custom#fzf#RgExcludeFilenames(<q-args>, <bang>0)
" }}}

" Grep {{{
if executable('rg')
    set grepprg=rg\ --vimgrep
endif

function! Grep(...)
  return system(join([&grepprg] + [expandcmd(join(a:000, ' '))], ' '))
endfunction

command! -nargs=+ -complete=file_in_path -bar Grep  cgetexpr Grep(<f-args>)
command! -nargs=+ -complete=file_in_path -bar LGrep lgetexpr Grep(<f-args>)

cnoreabbrev <expr> grep  (getcmdtype() ==# ':' && getcmdline() ==# 'grep')  ? 'Grep'  : 'grep'
cnoreabbrev <expr> lgrep (getcmdtype() ==# ':' && getcmdline() ==# 'lgrep') ? 'LGrep' : 'lgrep'

augroup quickfix
  autocmd!
  autocmd QuickFixCmdPost cgetexpr cwindow
  autocmd QuickFixCmdPost lgetexpr lwindow
augroup END
"}}}

" vim: set sw=2 ts=2 sts=0 expandtab fdm=marker :nospell:
