abbr -a vab      "vim ~/.config/fish/conf.d/abbreviations.fish"
abbr -a acc      "source .venv/bin/activate"
abbr -a d        "docker"
abbr -a dc       "docker compose"
abbr -a icat     "kitten icat"
abbr -a k        "kubectl"
abbr -a sd       "systemctl"
abbr -a sql      "sqlite3 -header -column"
abbr -a tt       "set_kitty_tab_title"
abbr -a v        "vim"
abbr -a vf       "vim (fzf)"
abbr -a g        "git"
abbr -a ga       "git add"
abbr -a gaa      "git add ."
abbr -a gap      "git add -p"
abbr -a gas      "git update-index --assume-unchanged"
abbr -a gns      "git update-index --no-assume-unchanged"
abbr -a gb       "git branch"
abbr -a gba      "git branch -a"
abbr -a gt       "git tag --sort -version:refname"
abbr -a gbd      "git branch -D"
abbr -a gc       "git commit"
abbr -a gca      "git commit -a"
abbr -a gcam     "git commit -a -m"
abbr -a gcan     "git commit --amend --no-edit"
abbr -a gcl      "git clone"
abbr -a gcm      "git commit -m"
abbr -a gco      "git checkout"
abbr -a gcub     "git fetch --prune && git for-each-ref --format '%(refname) %(upstream:track)' refs/heads | awk '\$2 == \"[gone]\" {sub(\"refs/heads/\", \"\", \$1); system(\"git branch -D \" \$1)}'"
abbr -a gd       "git diff"
abbr -a gf       "git fetch"
abbr -a gfm      "git fetch origin main:main"
abbr -a gl       "git log"
abbr -a glp      "git log --date=short --format='%C(green)%C(bold)%cd %C(auto)%h%d %s (%an)' --graph"
abbr -a gm       "git merge"
abbr -a gnew     "git checkout -b"
abbr -a gpf      "git push --force-with-lease"
abbr -a gpl      "git pull"
abbr -a gpr      "git pull --rebase"
abbr -a gps      "git push"
abbr -a gpsd     "git push --delete origin"
abbr -a gpso     "git push origin"
abbr -a gpsu     "git push --set-upstream origin"
abbr -a gr       "git reset"
abbr -a grh      "git reset --hard HEAD"
abbr -a gra      "git remote add"
abbr -a grb      "git rebase"
abbr -a grba     "git rebase --abort"
abbr -a grbc     "git rebase --continue"
abbr -a grbi     "git rebase -i"
abbr -a grbm     "git rebase main"
abbr -a grs      "git restore"
abbr -a grss     "git restore --staged"
abbr -a gst      "git stash"
abbr -a gsa      "git stash apply"
abbr -a gsl      "git stash list"
abbr -a gsp      "git stash pop"
abbr -a gss      "git status --short"
abbr -a gw       "git worktree"
abbr -a gwr      "git worktree remove"
abbr -a gwa      "git worktree add"
abbr -a ghpv     "gh pr view -w"
abbr -a ghpc     "gh pr create"
