# Abbreviations that set the cursor's position using %
abbr -a --set-cursor grp 'grep -rn "%" .'

# Regular abbreviations
abbr -a aa       "abduco -a"
abbr -a ab       "abduco"
abbr -a ac       "abduco -c"
abbr -a al       "abduco -l"
abbr -a ccp      "CLAUDE_CONFIG_DIR=\"$HOME/.claude-personal\" claude"
abbr -a d        "docker"
abbr -a dc       "docker compose"
abbr -a ec       "emacsclient -c"
abbr -a g        "git"
abbr -a ga       "git add"
abbr -a gaa      "git add ."
abbr -a gap      "git add -p"
abbr -a gas      "git update-index --assume-unchanged"
abbr -a gb       "git branch"
abbr -a gba      "git branch -a"
abbr -a gbd      "git branch -D"
abbr -a gC       "git -C"
abbr -a gc       "git commit"
abbr -a gca      "git commit -a"
abbr -a gcam     "git commit -a -m"
abbr -a gcan     "git commit --amend --no-edit"
abbr -a gcl      "git clone"
abbr -a gcm      "git commit -m"
abbr -a gd       "git diff"
abbr -a gf       "git fetch"
abbr -a gfm      "git fetch origin main:main"
abbr -a gl       "git log"
abbr -a glp      "git log --date=short --format='%C(green)%C(bold)%cd %C(auto)%h%d %s (%an)' --graph"
abbr -a gm       "git merge"
abbr -a gns      "git update-index --no-assume-unchanged"
abbr -a gpf      "git push --force-with-lease"
abbr -a gpl      "git pull"
abbr -a gps      "git push"
abbr -a gpsd     "git push --delete origin"
abbr -a gpso     "git push origin"
abbr -a gpsu     "git push --set-upstream"
abbr -a gr       "git reset"
abbr -a gra      "git remote add"
abbr -a grb      "git rebase"
abbr -a grbi     "git rebase -i"
abbr -a grbm     "git rebase main"
abbr -a grbr     "git rebase -i --root --committer-date-is-author-date"
abbr -a grh      "git reset --hard HEAD"
abbr -a grs      "git restore"
abbr -a grss     "git restore --staged"
abbr -a gss      "git status --short"
abbr -a gst      "git stash"
abbr -a gt       "git tag --sort -version:refname"
abbr -a gw       "git worktree"
abbr -a gwa      "git worktree add"
abbr -a gwr      "git worktree remove"
abbr -a icat     "kitten icat"
abbr -a k        "kubectl"
abbr -a n        "./nob"
abbr -a nb       "./nob build"
abbr -a nr       "./nob run"
abbr -a sql      "sqlite3 -header -column"
abbr -a ss       "sudo systemctl"
abbr -a v        "vim"
abbr -a v.       "vim ."
abbr -a vab      "vim ~/.config/fish/conf.d/abbreviations.fish"
abbr -a vis      "vim ~/dotfiles/SNIPPETS"
abbr -a z        "zoxide"
