clients:
  - type: openai-compatible
    name: ollama
    api_base: http://localhost:11434/v1
    models:
      - name: qwen2.5-coder:32b
        max_input_tokens: 131072
      - name: qwen2.5-coder:14b
        max_input_tokens: 131072
      - name: llama3.2:3b
        max_input_tokens: 2048
      - name: llama3.1:8b
        max_input_tokens: 32768
        supports_function_calling: true
      - name: llama3.2-vision
        max_input_tokens: 2048
        supports_vision: true
      - name: nomic-embed-text
        type: embedding
        default_chunk_size: 1000
        max_batch_size: 50
