#!/usr/bin/env zsh

# This script is called by the dark-mode-notify utility:
# https://github.com/bouk/dark-mode-notify

KITTY_CONF=~/dotfiles/kitty/kitty.conf

# Check if DARKMODE is set to 1
if [[ "$DARKMODE" = "1" ]]; then
  sed -i '' 's/  include/# include/' $KITTY_CONF
else
  sed -i '' 's/# include/  include/' $KITTY_CONF
fi

# Restart Kitty
kill -SIGUSR1 $(pgrep kitty)

# Refresh Colors in Vim
for pid in $(pgrep Vim); do
  kill -SIGUSR1 "$pid"
done
