#!/bin/zsh

# Check if DARKMODE is set to 1
if [[ "$DARKMODE" = "1" ]]; then
  sed -i '' 's/  include/# include/' ~/.config/kitty/kitty.conf
else
  sed -i '' 's/# include/  include/' ~/.config/kitty/kitty.conf
fi

# Restart Kitty
kill -SIGUSR1 $(pgrep kitty)

# Refresh Colors in Vim
for pid in $(pgrep Vim); do
  kill -SIGUSR1 $pid
done
