#!/bin/sh

PATH="/opt/homebrew/bin:/usr/bin:/bin:$PATH"

gpgconf --kill gpg-agent

if [ "$(uname)" = "Darwin" ]; then
  osascript -e 'display notification "🔒" with title "GPG Agent"'
else
  notify-send "GPG Agent" "🔒" 2>/dev/null || true
fi
