#!/bin/bash

project=$1
pod=`kubectl get pods --selector app.kubernetes.io/name=$1 -o json | jq -r '.items[0].metadata.name'`

cd ~/Projects/$project && find . -not -path '*node_modules*' -not -path '*.git*' -not -path '*test*' \
	| entr krsync -av --progress --stats --exclude 'node_modules' --exclude '.git' --exclude 'config/env' . $pod:/opt/bigpanda/$project
