#!/bin/bash

# Show logs with colored status in a single line in the following format:
# [<level>] <messageData.message> (<messageData.parameters>)

stern --output extjson "$@" | \
	jq --argjson levelmap '{ "info":"\u001b[32mINFO\u001b[0m", "debug":"\u001b[37mDEBUG\u001b[0m", "error":"\u001b[31mERROR\u001b[0m" }' \
	-Rr '. as $line | try (fromjson | "\u001b[1;35m\(.container)\u001b[0m: [\($levelmap[.message.level])] \u001b[0;44m\(.message.messageData.message)\u001b[0m (\(.message.messageData.parameters))") catch $line' | grep -v 'DEBUG'
