#!/bin/sh

if [ "$(uname)" = "Darwin" ]; then
  if [ -e "$HOME/.gnupg/ssh-mode" ]; then
    exec /opt/homebrew/bin/pinentry-curses "$@"
  else
    exec /opt/homebrew/bin/pinentry-mac "$@"
  fi
else
  exec /usr/bin/pinentry-curses "$@"
fi
