#!/usr/bin/env bash

SNIPPETS_FILE=~/dotfiles/SNIPPETS

if [ "$1" = "add" ]; then
  vim $SNIPPETS_FILE
  exit 0
fi

# Use fzf to select a description and fetch the associated command
selected_description=$(
  awk '/^#/ {print substr($0, 3)}' $SNIPPETS_FILE | \
    fzf --preview="awk '/# '{}'/ {getline; print}' $SNIPPETS_FILE | bat -l zsh -p --color always -" \
    --preview-window=up:3:wrap \
    --bind='ctrl-y:preview-up,ctrl-e:preview-down'
)

# If no description is selected, exit
[ -z "$selected_description" ] && exit 1

# Fetch the associated command for the selected description from the text files
associated_command=$(awk -v desc="# $selected_description" '$0 == desc {getline; print}' $SNIPPETS_FILE )

# Edit the command in Vim and add it to the clipboard before quitting
echo "$associated_command" | pbcopy
