#!/bin/zsh

# Use fzf to select a description and fetch the associated command
selected_description=$(find -L "$SNIPPET_DIR" -type f -exec awk '/^#/ {print substr($0, 3)}' {} + | fzf --preview='fname=$(rg -F -l {} $SNIPPET_DIR); bat -l zsh -p --color always $fname' --bind='ctrl-y:preview-up,ctrl-e:preview-down')

# If no description is selected, exit
[ -z "$selected_description" ] && exit 1

# Fetch the associated command for the selected description from the text files
associated_command=$(find -L "$SNIPPET_DIR" -type f -exec awk -v desc="# $selected_description" '$0 == desc {getline; print}' {} +)

# Edit the command in Vim and on leave add it to the clipboard
echo $associated_command | vim -c "set ft=sh" -c "nmap <leader>q :q!<CR>" -c "autocmd VimLeave * execute 'normal! ggVG\"*y'" -
