#!/bin/zsh

# Use fzf to select a description and fetch the associated command
selected_description=$(find -L "$SNIPPET_DIR" -type f -exec awk '/^#/ {print substr($0, 3)}' {} + | fzf --preview='fname=$(rg -F -l {} $SNIPPET_DIR); bat -l zsh -p --color always $fname' --bind='ctrl-y:preview-up,ctrl-e:preview-down')

# If no description is selected, exit
[ -z "$selected_description" ] && exit 1

# Fetch the associated command for the selected description from the text files
associated_command=$(find -L "$SNIPPET_DIR" -type f -exec awk -v desc="# $selected_description" '$0 == desc {getline; print}' {} +)

# Copy the command to the tmux buffer and paste it
tmux set-buffer "$associated_command"
{ sleep .10; tmux paste-buffer; } &
