color0               {{black}}
color8               {{brightblack}}
color1               {{red}}
color9               {{brightred}}
color2               {{green}}
color10              {{brightgreen}}
color3               {{orange}}
color11              {{yellow}}
color4               {{blue}}
color12              {{brightblue}}
color5               {{magenta}}
color13              {{brightmagenta}}
color6               {{cyan}}
color14              {{brightcyan}}
color7               {{gray}}
color15              {{white}}

background           {{black}}
foreground           {{white}}
cursor               {{yellow}}
selection_background {{ui}}
selection_foreground {{yellow}}
active_border_color  {{green}}
mark1_foreground     {{red}}
mark1_background     {{black}}
mark2_foreground     {{yellow}}
mark2_background     {{black}}
mark3_foreground     {{green}}
mark3_background     {{black}}
