airblade/vim-gitgutter
airblade/vim-rooter
ap/vim-css-color
christoomey/vim-tmux-navigator
hrsh7th/vim-vsnip
junegunn/fzf
junegunn/fzf.vim
junegunn/vim-easy-align
justinmk/vim-sneak
mattn/emmet-vim
NLKNguyen/papercolor-theme
preservim/vimux
ruanyl/vim-gh-line
tpope/vim-rsi
tpope/vim-endwise
tpope/vim-characterize
tpope/vim-commentary
tpope/vim-dispatch
tpope/vim-fugitive
tpope/vim-repeat
tpope/vim-surround
tpope/vim-unimpaired
tpope/vim-vinegar
Yggdroot/indentLine
neovim/nvim-lspconfig
