;;; guychouk color scheme -*- lexical-binding: t -*-

(deftheme guychouk "guychouk color scheme")

(let ((bg         "#151515")
      (ui         "#2c2c2c")
      (fg         "#e8e1cf")
      (gray       "#808080")
      (red        "#fb413a")
      (green      "#7ed68a")
      (orange     "#e58a2b")
      (yellow     "#d8b65a")
      (magenta    "#d97aad")
      (brightblue "#8295b1"))
  (custom-theme-set-faces
   'guychouk
   `(default                      ((t (:foreground ,fg :background ,bg))))
   `(cursor                       ((t (:background ,yellow))))
   `(region                       ((t (:foreground ,yellow :background ,ui))))
   `(hl-line                      ((t (:background ,gray))))
   `(fringe                       ((t (:background ,bg))))
   `(minibuffer-prompt            ((t (:foreground ,magenta))))
   `(mode-line                    ((t (:foreground ,fg :background ,ui :box nil))))
   `(mode-line-inactive           ((t (:foreground ,gray :background ,ui :box nil))))
   `(line-number                  ((t (:foreground ,gray :background ,bg))))
   `(line-number-current-line     ((t (:foreground ,magenta :background ,bg :weight bold))))
   `(font-lock-comment-face       ((t (:foreground ,gray :slant italic))))
   `(font-lock-string-face        ((t (:foreground ,green))))
   `(font-lock-keyword-face       ((t (:foreground ,magenta))))
   `(font-lock-function-name-face ((t (:foreground ,fg))))
   `(font-lock-variable-name-face ((t (:foreground ,magenta))))
   `(font-lock-type-face          ((t (:foreground ,magenta))))
   `(font-lock-constant-face      ((t (:foreground ,magenta))))
   `(font-lock-builtin-face       ((t (:foreground ,magenta))))
   `(font-lock-preprocessor-face  ((t (:foreground ,fg))))
   `(font-lock-warning-face       ((t (:foreground ,red))))
   `(error                        ((t (:foreground ,red))))
   `(warning                      ((t (:foreground ,orange))))
   `(success                      ((t (:foreground ,green))))
   `(match                        ((t (:foreground ,yellow :background ,ui))))
   `(isearch                      ((t (:foreground ,bg :background ,yellow))))
   `(lazy-highlight               ((t (:foreground ,bg :background ,brightblue))))
   `(vertical-border              ((t (:foreground ,ui))))
   `(show-paren-match             ((t (:foreground ,bg :background ,fg :weight bold))))
   `(header-line                  ((t (:foreground ,fg :background ,ui))))))

(provide-theme 'guychouk)
